import React from 'react'
import { useRouter} from 'next/router'
import { useState, useEffect } from 'react'
import DefaultLayout from '../../layouts/Default'
import Head from 'next/head'

export default function Cat() {

    const [cat, setCat] = useState(null)

    const router = useRouter()
    const {id} = router.query

    const fetchCat = async () =>{
    

        const response = await fetch(`/api/cats/${id}`)
        const data = await response.json()
        setCat(data)
}

useEffect(()=>{
    fetchCat()
}, [])


  return (
    
    <div>
    <DefaultLayout> 
    <div>    
        {cat && (
        <>
        <Head>
        <title>{cat.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="container mt-5" id="smartphone">
        <img src={cat.image.url} alt={cat.image.alt}  id="cat"/>
        <div className="mx-5">
            <h1>{cat.name}</h1>
            <p>{cat.description}</p>
        </div>
        </div>
        
    </>) }</div>
    </DefaultLayout> 
    </div>
    
  )
}
